### ISSUE TITLE
Advanced Analytics is not working well

### ISSUE THREAD

**Issue by miniesam** [cydrobolt/polr#544]
## Expected Behavior

Turn on the `Advanced Analytics` feature and make the Polr operate normally.

## Current Behavior

When I turn on the `Advanced Analytics` function at the initial setup, the error occurs.

## Possible Solution

I think the `Advanced Analytics`'s bug should be fixed.

## Steps to Reproduce (for bugs)

1. I followed the [Vultr's tutorial](https://www.vultr.com/docs/install-polr-on-ubuntu-18-04).
2. Navigate to `example.com/setup` to setup the Polr.
3. Check on `Enable advanced analytics` option which is at `Advanced Analytics` to use analytics feature.
4. Click the green `Install` button and watch if the error appears.

## Context

A few days ago, I tried to install Polr on my server for the first time.
But they kept saying there was a problem and it didn't go smoothly.
I've tried the installation dozens of times, and the initial setup didn't finish properly when I turned on the `Advanced Analytics` feature.
So I think the `Advanced Analytics` function has a bug, please check it as soon as possible.

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc): macOS Mojave, Chrome 79, Amazon Lightsail, Ubuntu 18.04 LTS
* Instance link (optional):

**Comment by grfbr** [comment]
Hi!

I believe that I was having the same problem! And the issue is related to the MaxMind database. Since Dec 2019, is not possible to download the file without login!

I fixed it going to the MaxMind website, doing the signup and modifying the Geolocation library.

1. Go to https://dev.maxmind.com/geoip/geoip2/geolite2/ and make the sign-up;
2. After finish the sign-up, in the bottom of the page have the link "GeoIP2 / GeoLite2 - Download files";
3. Copy the GeoLite2-City GZIP Link; 
4. Go to file config/geoip.php and change the line 57 with the link that you copied;

After this, you can try to install the system again or just run the command php artisan geoip:update

I hope it helps you! :)

Cheers

**Comment by GomoDD** [comment]
@grfbr I've done that (also mentioned in https://github.com/cydrobolt/polr/issues/540) and successfully updated the database via "php artisan geoip:update" but the location tracking part still isn't working. Could you contact me (on Twitter @Gomo_DD) and help troubleshoot the issue? I'd appreciate it / make it worth your while!
